In [3]:
import numpy as np
import pandas as pd

In [4]:
obj = pd.Series([4,3,5,6])

In [5]:
obj

0    4
1    3
2    5
3    6
dtype: int64

In [6]:
obj.array

<NumpyExtensionArray>
[4, 3, 5, 6]
Length: 4, dtype: int64

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([2,3,4,1], index = ["a","b","c","d"])

In [9]:
obj2

a    2
b    3
c    4
d    1
dtype: int64

In [10]:
obj2["a"]

np.int64(2)

In [11]:
obj2[obj2>1]

a    2
b    3
c    4
dtype: int64

In [12]:
np.exp(obj2)

a     7.389056
b    20.085537
c    54.598150
d     2.718282
dtype: float64

In [13]:
"e" in obj2

False

In [14]:
"a" in obj2

True

In [15]:
directory = {"Arun":8015656774, "Sham": 9042882993, "Dad":9442332569}

obj3 = pd.Series(directory)

In [16]:
obj3

Arun    8015656774
Sham    9042882993
Dad     9442332569
dtype: int64

In [17]:
directory

{'Arun': 8015656774, 'Sham': 9042882993, 'Dad': 9442332569}

In [18]:
obj3.to_dict()

{'Arun': 8015656774, 'Sham': 9042882993, 'Dad': 9442332569}

In [19]:
obj3.to_csv()

',0\nArun,8015656774\nSham,9042882993\nDad,9442332569\n'

In [20]:
family = ["Arun","Dad","Sham","Mom"]

obj4 = pd.Series(directory, index = family)

In [21]:
obj4

Arun    8.015657e+09
Dad     9.442333e+09
Sham    9.042883e+09
Mom              NaN
dtype: float64

In [22]:
obj4.isna()

Arun    False
Dad     False
Sham    False
Mom      True
dtype: bool

In [23]:
obj4.notna()

Arun     True
Dad      True
Sham     True
Mom     False
dtype: bool

In [24]:
obj + obj2 + obj3 + obj4

0      NaN
1      NaN
2      NaN
3      NaN
Arun   NaN
Dad    NaN
Mom    NaN
Sham   NaN
a      NaN
b      NaN
c      NaN
d      NaN
dtype: float64

In [25]:
obj3 + obj4

Arun    1.603131e+10
Dad     1.888467e+10
Mom              NaN
Sham    1.808577e+10
dtype: float64

In [26]:
obj4.index.name = "family"

In [27]:
obj4

family
Arun    8.015657e+09
Dad     9.442333e+09
Sham    9.042883e+09
Mom              NaN
dtype: float64

In [28]:
obj4.name="mobile"

In [29]:
obj4

family
Arun    8.015657e+09
Dad     9.442333e+09
Sham    9.042883e+09
Mom              NaN
Name: mobile, dtype: float64

In [30]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [31]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
frame.head(2)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [33]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns=["year","state","pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [37]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [38]:
frame.iloc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [39]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
frame["debt"] = 16.5

In [41]:
frame

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [42]:
frame["debt"]=np.arange(6.)

In [43]:
frame

    state  year  pop  debt
0    Ohio  2000  1.5   0.0
1    Ohio  2001  1.7   1.0
2    Ohio  2002  3.6   2.0
3  Nevada  2001  2.4   3.0
4  Nevada  2002  2.9   4.0
5  Nevada  2003  3.2   5.0

In [44]:
del frame["debt"]

In [45]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [47]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [48]:
frame2 = pd.DataFrame(populations)

In [49]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [50]:
frame2.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [51]:
frame2.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [52]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [53]:
frame2.index.name="year"

In [54]:
frame2

      Ohio  Nevada
year
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [55]:
frame2.columns.name = "states"

In [56]:
frame2

states  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [57]:
frame2.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [60]:
frame2

states  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [61]:
# Index Objects

In [66]:
import numpy as np
import pandas as pd

obj = pd.Series(np.arange(3), index = ["a", "b", "c"])

index = obj.index

index[1:]

Index(['b', 'c'], dtype='str')

In [68]:
index[1]= "d"

# Index objects are immutable and thus can't be modified by user

TypeError: Index does not support mutable operations

In [71]:
labels = pd.Index(np.arange(3))

labels

obj5 = pd.Series([1.5, -2.5, 0], index=labels)

obj5

0    1.5
1   -2.5
2    0.0
dtype: float64

In [72]:
obj5.index is labels

True

In [73]:
frame2

states  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [75]:
frame2.columns

"Ohio" in frame2.columns

True

In [76]:
2003 in frame2.index

False

In [77]:
# pandas indexes can have duplicate

In [78]:
# Essential Functionality

In [80]:
obj6 = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d","a","c","b"])

obj6

d    4.5
a    7.2
c   -5.3
b    3.6
dtype: float64

In [93]:
obj7 = obj6.reindex(["a","b","c","d","e"])

obj7

a    7.2
b    3.6
c   -5.3
d    4.5
e    NaN
dtype: float64

In [94]:
frame3 = pd.DataFrame(np.arange(9).reshape((3,3)),index = ["a","c","b"],
                      columns=["Ohio","Texas","California"])

frame3

   Ohio  Texas  California
a     0      1           2
c     3      4           5
b     6      7           8

In [95]:
frame4 = frame3.reindex(index=["a","b","c","d"])
frame4

   Ohio  Texas  California
a   0.0    1.0         2.0
b   6.0    7.0         8.0
c   3.0    4.0         5.0
d   NaN    NaN         NaN

In [97]:
states = ["Texas","Ohio","Cali"]

frame4.reindex(columns=states)

   Texas  Ohio  Cali
a    1.0   0.0   NaN
b    7.0   6.0   NaN
c    4.0   3.0   NaN
d    NaN   NaN   NaN

In [99]:
frame4.loc[["a","b","c"], ["Texas","Ohio"]]

frame4

   Ohio  Texas  California
a   0.0    1.0         2.0
b   6.0    7.0         8.0
c   3.0    4.0         5.0
d   NaN    NaN         NaN

In [100]:
# Dropping Entries from an Axis

In [101]:
obj = pd.Series(np.arange(5.), index=["a","b","c","d","e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [102]:
obj.drop("b")

a    0.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [103]:
obj.drop(["a","c"])

b    1.0
d    3.0
e    4.0
dtype: float64

In [104]:
frame3

   Ohio  Texas  California
a     0      1           2
c     3      4           5
b     6      7           8

In [107]:
frame4

   Ohio  Texas  California
a   0.0    1.0         2.0
b   6.0    7.0         8.0
c   3.0    4.0         5.0
d   NaN    NaN         NaN

In [108]:
frame4.drop(index=["a"])

   Ohio  Texas  California
b   6.0    7.0         8.0
c   3.0    4.0         5.0
d   NaN    NaN         NaN

In [109]:
frame2

states  Ohio  Nevada
year
2000     1.5     NaN
2001     1.7     2.4
2002     3.6     2.9

In [110]:
frame5 = frame2.reindex(["a","b","c"])

In [111]:
frame5

states  Ohio  Nevada
year
a        NaN     NaN
b        NaN     NaN
c        NaN     NaN

In [114]:
frame5.drop(columns=["Nevada"])

states  Ohio
year
a        NaN
b        NaN
c        NaN

In [115]:
# Indexing, Selection and Filtering

In [116]:
obj = pd.Series(np.arange(4.), index=["a","b","c","d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [117]:
obj["b"]

np.float64(1.0)

In [120]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [121]:
obj[["b","a","c"]]

b    1.0
a    0.0
c    2.0
dtype: float64

In [124]:
obj.iloc[[1, 2]]

b    1.0
c    2.0
dtype: float64

In [125]:
obj[obj< 2]

a    0.0
b    1.0
dtype: float64

In [126]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

In [127]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [130]:
data[["one","three"]]

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [131]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [133]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [135]:
data[data < 5 ] = 0

In [136]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [139]:
data.iloc[1]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [140]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [141]:
data.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='str')

In [142]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [144]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [145]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [148]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [149]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [150]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [151]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

In [152]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [153]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [154]:
df2.loc[1,"b"] = np.nan

In [155]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [156]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [157]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [158]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [159]:
frame5

states  Ohio  Nevada
year
a        NaN     NaN
b        NaN     NaN
c        NaN     NaN

In [160]:
frame3

   Ohio  Texas  California
a     0      1           2
c     3      4           5
b     6      7           8

In [161]:
series = frame3.iloc[0]

In [162]:
series

Ohio          0
Texas         1
California    2
Name: a, dtype: int64

In [163]:
frame3 - series

   Ohio  Texas  California
a     0      0           0
c     3      3           3
b     6      6           6

In [164]:
frame3 + series

   Ohio  Texas  California
a     0      2           4
c     3      5           7
b     6      8          10

In [165]:
# Function Application and Mapping

In [166]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [167]:
frame

               b         d         e
Utah    0.075925 -0.178736  0.652994
Ohio   -1.893884  1.331051 -0.199139
Texas   0.455511  0.356729  0.309707
Oregon  0.047892 -0.887978 -0.086801

In [168]:
np.abs(frame)

               b         d         e
Utah    0.075925  0.178736  0.652994
Ohio    1.893884  1.331051  0.199139
Texas   0.455511  0.356729  0.309707
Oregon  0.047892  0.887978  0.086801

In [169]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

b    2.349394
d    2.219029
e    0.852134
dtype: float64

In [170]:
frame.apply(f1, axis="columns")

Utah      0.831731
Ohio      3.224934
Texas     0.145804
Oregon    0.935870
dtype: float64

In [171]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

            b         d         e
min -1.893884 -0.887978 -0.199139
max  0.455511  1.331051  0.652994

In [172]:
frame

               b         d         e
Utah    0.075925 -0.178736  0.652994
Ohio   -1.893884  1.331051 -0.199139
Texas   0.455511  0.356729  0.309707
Oregon  0.047892 -0.887978 -0.086801

In [176]:
def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

            b      d      e
Utah     0.08  -0.18   0.65
Ohio    -1.89   1.33  -0.20
Texas    0.46   0.36   0.31
Oregon   0.05  -0.89  -0.09

In [177]:
# Sorting and Indexing

In [178]:
obj = pd.Series(np.arange(5), index= ["a","b","c","d","e"])

In [179]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [182]:
obj1 = obj.reindex(["e","a","d","b","c"])

In [183]:
obj1

e    4
a    0
d    3
b    1
c    2
dtype: int64

In [184]:
obj1.sort_index()

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [186]:
obj1

e    4
a    0
d    3
b    1
c    2
dtype: int64

In [187]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"])

In [188]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [189]:
frame.sort_index(axis="columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [191]:
frame.sort_index(axis="columns", ascending=True)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [192]:
obj= pd.Series([4, np.nan, -3, 2])

In [193]:
obj

0    4.0
1    NaN
2   -3.0
3    2.0
dtype: float64

In [194]:
obj.sort_index()

0    4.0
1    NaN
2   -3.0
3    2.0
dtype: float64

In [196]:
obj.sort_values()

2   -3.0
3    2.0
0    4.0
1    NaN
dtype: float64

In [198]:
obj.sort_values(na_position="first")

1    NaN
2   -3.0
3    2.0
0    4.0
dtype: float64

In [200]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [202]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [203]:
# Axis Indexes and Duplicate labels

In [204]:
obj.is_unique

False

In [205]:
df1.describe()

         a    b     c     d
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [206]:
df1.count()

a    3
b    3
c    3
d    3
dtype: int64

In [207]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [208]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [209]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: str

In [210]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [211]:
# Correlation and Covariance

In [213]:
pwd

'/Users/arunsankarask/ASK Second Brain/Skills/Python Mentor/Python Practice/pandas'

In [216]:
import numpy as np
import pandas as pd

# BoE nominal spot curve, [as-of date] -- from "GLC Nominal daily data current month.xlsx"
tenors = [0.5, 1, 2, 5, 10, 30]
zero_rates_pct = [4.14, 4.37, 4.56, 4.78, 5.19, 5.73]

zero_rate = pd.Series(zero_rates_pct, index=tenors)
zero_rate = zero_rate * 0.01

print(zero_rate)

0.5     0.0414
1.0     0.0437
2.0     0.0456
5.0     0.0478
10.0    0.0519
30.0    0.0573
dtype: float64

In [1]:
import timeit
n = 1_000_000
lst, st = list(range(n)), set(range(n))
print(timeit.timeit(lambda: (n - 1) in lst, number=100))  # scans all n elements
print(timeit.timeit(lambda: (n - 1) in st,  number=100))  # jumps straight there

0.3612170420237817
3.5830307751893997e-06